
[en]
  title = "Jobs – ReproJobs"
  LanguageName = "English"
  weight = 1

[es]
  title = "Trabajo – ReproJobs" # just for the sake of showing this is possible
  LanguageName = "Español"
  weight = 2
