# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on regular cron intervals. Schedule is approximate.
  schedule:
  - cron:  '* */8 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
 
      # Add environment variables
      - name: Env vars
        run: |
          echo "AIRTABLE_API_KEY=${{ secrets.AIRTABLE_API_KEY }}" >> $GITHUB_ENV
          echo "AIRTABLE_BASE_ID=${{ secrets.AIRTABLE_BASE_ID }}" >> $GITHUB_ENV
      
      # Install dependencies for the jobsboard to fetch content from airtable.
      - name: NPM install
        run: npm install

      # Fetch new data from Airtable
      - name: Run Airtable script
        run: npm run generate:jobs
      
      # Rebuild the site with the new content
      - name: Run Airtable script
        run: npm run build
