# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on regular cron intervals. Schedule is approximate.
  schedule:
  - cron:  '*/5 * * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup git config and auth
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          # Hard-code user configuration.
          git config user.email "rae@throneless.tech"
          git config user.name "Rae Throneless Tech"

      - name: Make deploy scripts executable
        run: |
          chmod +x ./deploy/install.sh
          chmod +x ./deploy/generate.sh

      - name: Install dependencies
        run: ./deploy/install.sh

      - name: Remove existing content
        # NOTE: if the directory names change, then this will fail and stop
        # execution.
        run: |
          find content/post static/images \
           -type f -not -name "_index.md" -not -name ".gitkeep" -delete

      - name: Generate new content
        run: ./deploy/generate.sh
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}

      - name: Commit generated content
      # NOTE: if generate does not create the directories below, then this will
      # fail and stop execution. There should be no commit when there is no
      # change.
        run: |
         git add content/post static/images
         # Only commit and push if there were effective changes.
          if !(git diff --quiet && git diff --staged --quiet) ; then
           git commit -m "CRON ACTION: CI to update content from Airtable"
            git push origin main
         fi
